name: Netlify variables

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: "Update env to netlify"
        run: node ./.github/scripts/environments.js
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_LABELS: ${{ github.event.pull_request.labels }}
