name: Netlify variables

on:
  pull_request:
    types: [labeled]

jobs:
  setup-split-test:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: install netlify cli
        uses: npm install netlify-cli -g

      - name: "Update env to netlify"
        if: contains(github.event.pull_request.labels.*.name, 'split-test')
        run: node ./.github/scripts/environments.js
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
