name: Split test

on:
  pull_request:
    types: [labeled, closed]

jobs:
  setup:
    if: contains(github.event.pull_request.labels.*.name, 'split-test') && github.event.pull_request.state != 'closed'
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: install netlify cli
        run: npm install netlify-cli@12.0.0 -g --loglevel=error

      - name: "Setup script"
        run: node ./.github/scripts/setup-split-test.js
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          BRANCH: ${{ github.head_ref }}
          SITE_ID: ${{ secrets.SITE_ID }}

  cleanup:
    if: github.event.action == 'closed'
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: install netlify cli
        run: npm install netlify-cli@12.0.0 -g --loglevel=error

      - name: "Cleanup script"
        if: github.event.action == 'closed'
        run: node ./.github/scripts/remove-branch-env.js
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          BRANCH: ${{ github.head_ref }}
          SITE_ID: 08a94377-dc9d-4a7e-a460-d465edb91e12
